### Задание №1

In [2]:
import numpy as np

In [6]:
a = np.array([
    [1, 2, 3, 3, 1],
    [6, 8, 11, 10, 7]
]).T

In [7]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
mean_a = np.mean(a, axis = 0)

In [9]:
mean_a

array([2. , 8.4])

### Задание №2

In [10]:
a_centered = a - mean_a

In [11]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание № 3

In [18]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [19]:
a_centered_sp

8.0

In [20]:
a_cov = a_centered_sp / (len(a) - 1)

In [21]:
a_cov

2.0

### Задание № 4

In [22]:
a_cov2 = np.cov(a.T)

In [23]:
a_cov2

array([[1. , 2. ],
       [2. , 4.3]])